### PR TITLE
Update lock file.

### PR DESCRIPTION
**Pull request by rosiel**
Fixes that thing where the install profile is locked to [`dev-april-config-reconciliation`](https://github.com/Islandora-Devops/islandora-sandbox/blob/main/composer.lock#L9795). 

And updates other libraries/modules.

### CODE REVIEW

**Comment by rosiel** [comment]
Testing instructions:

ISLE: Open Makefile and edit the `-b main https://github.com/Islandora-Devops/islandora-sandbox` line to `-b update-lock  https://github.com/rosiel/islandora-sandbox`.  Continue to `make local`.

Playbook: Open `vars/demo.yml` and set 
```
drupal_deploy_repo: https://github.com/islandora-devops/islandora-sandbox
drupal_deploy_version: install-profile
``` 
to
```
drupal_deploy_repo: https://github.com/rosiel/islandora-sandbox
drupal_deploy_version: update-lock
```
Make sure `demo` is the profile in the Vagrantfile, and vagrant up.

**Comment by DonRichards** [comment]
We should make a section in the readme for each repo on how to test, like your last comment.

**Comment by DonRichards** [comment]
Not with this PR, but just saying.

**Comment by DonRichards** [comment]
Tested in Isle, and it looks good!! Thanks, @rosiel, for doing this so quickly!

**Review by DonRichards — APPROVED** [review]

**Pull request merged**
