### PR TITLE
Add user redirect back after login

### PR DESCRIPTION
**Pull request by DonRichards**
Something kinda annoying trying to go to a page you don't have access to. Normally the user should get a 403 page. This isn't set yet. I added a redirect to the login page and a "destination" to go back to the page that originally triggered the 403 page.

### CODE REVIEW

**Comment by rosiel** [comment]
This would be nice in https://github.com/Islandora-Devops/islandora_install_profile_demo since the recent refactor moved all config files there.

**Comment by DonRichards** [comment]
@rosiel Done. https://github.com/Islandora-Devops/islandora_install_profile_demo/pull/8

**Comment by alxp** [comment]
Should this issue be closed in that case?

**Comment by DonRichards** [comment]
Thanks guys

**Pull request closed without merging**
